# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pug < Formula
  desc "Terminal user interface for terraform power users."
  homepage "https://github.com/leg100/pug"
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/leg100/pug/releases/download/v0.3.1/pug_0.3.1_darwin_amd64.zip"
      sha256 "5b0216c3883763710067ee533ed3f29cb2a78c3f36f6f02e5f3f804f6833c6bb"

      def install
        bin.install "pug"
      end
    end
    on_arm do
      url "https://github.com/leg100/pug/releases/download/v0.3.1/pug_0.3.1_darwin_arm64.zip"
      sha256 "6740040f6eb01327247389fdf7075bd14217a4c872862a59425e6febffc20535"

      def install
        bin.install "pug"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leg100/pug/releases/download/v0.3.1/pug_0.3.1_linux_amd64.zip"
        sha256 "d927bf6c6fff283b6bb2f96e8d2c30a8ddec20f422a6f6fedf969ed6f60439fa"

        def install
          bin.install "pug"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leg100/pug/releases/download/v0.3.1/pug_0.3.1_linux_arm64.zip"
        sha256 "db812fb7bbbce204bef3421fe58ae5aaf3360ec071684d243bb17c3365ebba55"

        def install
          bin.install "pug"
        end
      end
    end
  end
end
