# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pug < Formula
  desc "Terminal user interface for terraform power users."
  homepage "https://github.com/leg100/pug"
  version "0.5.2"

  on_macos do
    on_intel do
      url "https://github.com/leg100/pug/releases/download/v0.5.2/pug_0.5.2_darwin_amd64.zip"
      sha256 "5925c84289610606d373627d95a4a376cdc89cec3d98bdf60ee4bd03c66e60bc"

      def install
        bin.install "pug"
      end
    end
    on_arm do
      url "https://github.com/leg100/pug/releases/download/v0.5.2/pug_0.5.2_darwin_arm64.zip"
      sha256 "ceb2b0e032b86f1e3563f308d755a94aa0e7590ea131e3a8f0653c8329a286c2"

      def install
        bin.install "pug"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leg100/pug/releases/download/v0.5.2/pug_0.5.2_linux_amd64.zip"
        sha256 "1b1f97a85e49d857cc559b58508b37316114be246c4bca838a739759808bb645"

        def install
          bin.install "pug"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leg100/pug/releases/download/v0.5.2/pug_0.5.2_linux_arm64.zip"
        sha256 "bd1a49da895d562797d9e01bf8d5784bfdfde4923858034f169c2891738ac070"

        def install
          bin.install "pug"
        end
      end
    end
  end
end
